version: "3"
services:
  tomcat:
    image: "mytomcat"
    ports:
      - "8080-8085:8080"
  httpd:
    image: "httpd"
    ports:
      - "80-85:80"
    volumes:
      - "/mnt/html:/usr/local/apache2/htdocs/"
      

